apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: podpvc
  namespace: qq2
spec:
  accessModes:
    - ReadWriteOnce    # Allows multiple pods to read from this PVC
  resources:
    requests:
      storage: 1Gi  # Adjust the storage size as needed

---
apiVersion: v1
kind: Pod
metadata:
  name: pod
  namespace: qq2
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - mountPath: /data
          name: data-volume
          readOnly: true
  volumes:
    - name: data-volume
      persistentVolumeClaim:
        claimName: podpvc