apiVersion: v1
kind: Pod
metadata:
  name: pod
  namespace: qq2
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
    volumeMounts:
    - name: nginx-data
      mountPath: /data
      readOnly: true
  volumes:
  - name: nginx-data
    persistentVolumeClaim:
      claimName: podpvc