apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: podpvc  # Name of the PVC 
spec:
  accessModes:
  - ReadOnlyMany  # PVC is read-only
  resources:
    requests:
      storage: 1Gi 
---

apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: nginx
      image: nginx:latest
      volumeMounts:
      - mountPath: /data
        name: data-volume
  volumes:
    - name: data-volume
      persistentVolumeClaim:
        claimName: podpvc
