apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: podpvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard

---

apiVersion: v1
kind: Pod
metadata:
  name: pod
  namespace: qq2
spec:
  containers:
  - name: nginx
    image: nginx:latest
    volumeMounts:
    - mountPath: /data
      name: mount-volume
      readOnly: true
  volumes:
  - name: mount-volume
    persistentVolumeClaim:
      claimName: podpvc


