apiVersion: v1
kind: Pod
metadata:
  name: pod
spec:
  containers:
  - name: nginx
    image: nginx:latest
    volumeMounts:
    - mountPath: /root/data
      name: data-volume
      readOnly: true
  volumes:
  - name: data-volume
    persistentVolumeClaim:
      claimName: podpvc