apiVersion: v1
kind: Pod
metadata:
  name: pod
spec:
  containers:
  - name: nginx
    image: nginx:latest
    volumeMounts:
    - mountPath: /data
      name: data-volume
      readOnly: true
  volumes:
  - name: data-volume
    persistentVolumeClaim:
      claimName: podpvc
controlplane $ cat podpvc.yaml 
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: podpvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  
  storageClassName: gp2