apiVersion: v1
kind: Pod
metadata:
  name: pod
  namespace: qq2
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: data-volume
      mountPath: /data
      readOnly: true
  volumes:
  - name: data-volume
    persistentVolumeClaim:
      claimName: podpvc
