apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-ass3
  labels:
    app: postgres-ass3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-ass3
  template:
    metadata:
      labels:
        app: postgres-ass3
    spec:
      containers:
      - name: postgres-docker-ass3
        image: postgres
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret
              key: POSTGRES_PASSWORD
        volumeMounts:
        - mountPath: /var/lib/pgadmin
          name: local-storage-ass3
      volumes:
        - name: local-storage-ass3
          persistentVolumeClaim:
              claimName: pvc-ass3

---;

apiVersion: v1
kind: Service
metadata:
  name: postgres-svc-ass3
spec:
  type: ClusterIP
  selector:
    app: postgres-ass3
  ports:
    - port: 5432
      targetPort: 5432
