apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresconfig
data:
  POSTGRES_USER: "admin"
---
apiVersion: v1
kind: Secret
metadata:
  name: postgressecret
type: Opaque
data:
  POSTGRES_PASSWORD: YWRtaW4=
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: question16
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  storageClassName: question16
  hostPath:
    path: /mnt/data/postgres
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: question16
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-deployment
  template:
    metadata:
      labels:
        app: postgres-deployment
    spec:
      containers:
        - name: postgres-deployment
          image: postgres:latest
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgressecret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: postgresconfig
                  key: POSTGRES_USER
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-vol
              mountPath: /var/lib/postgres
      volumes:
        - name: postgres-vol
          persistentVolumeClaim:
            claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres-deployment
