apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-ass3
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  hostPath:
    path: "/mnt/data/"
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: local-storage-ass3
