apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-ass3
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage-ass3
