apiVersion: v1
kind: Pod
metadata:
  name: apache
  namespace: default
spec:
  containers:
    - name: apache
      image: httpd
      env:
        - name: CONTENT
          valueFrom:
            configMapKeyRef:
              name: q5
              key: ME_CONFIG_BASICAUTH_USERNAME  # This key contains the username for basic auth
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: credentials
              key: MONGO_INITDB_ROOT_USERNAME  # This key contains the root username
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: credentials
              key: MONGO_INITDB_ROOT_PASSWORD  # This key contains the root password