apiVersion: v1
kind: ConfigMap
metadata:
  name: q5
  namespace: default
data:
  content: myapp_database
---
apiVersion: v1
kind: Secret
metadata:
  name: credentials
  namespace: default
type: Opaque
data:
  username: YWRtaW4K # base64 encoded 'admin'
  password: YWRtaW4K # base64 encoded 'admin'
---
apiVersion: v1
kind: Pod
metadata:
  name: apache
  namespace: default
spec:
  containers:
    - name: apache
      image: httpd:latest
      env:
        - name: CONTENT
          valueFrom:
            configMapKeyRef:
              name: q5
              key: content
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: credentials
              key: username
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: credentials
              key: password
