apiVersion: v1
kind: ConfigMap
metadata:
  name: q5
data:
  content: "Mock exam 2"

  ---

  apiVersion: v1
kind: Secret
metadata:
  name: credentials
  namespace: default
type: Opaque
data:
  username: YXRoaXJhaAo= # base64 for 'username'
  password: bXkgcGFzc3dvcmQK  # base64 for 'password'

---

apiVersion: v1
kind: Pod
metadata:
  name: apache
  namespace: default
spec:
  containers:
    - name: apache
      image: httpd:latest
      env:
        - name: CONTENT
          valueFrom:
            configMapKeyRef:
              name: q5
              key: content
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: credentials
              key: username
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: credentials
              key: password