apiVersion: v1
kind: Pod
metadata:
  name: apache
  namespace: default
spec:
  containers:
  - name: apache
    image: httpd
    env:
    - name: CONTENT
      valueFrom:
        configMapKeyRef:
          name: q5
          key: content
    - name: USERNAME
      valueFrom:
        secretKeyRef:
          name: credentials
          key: username
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: credentials
          key: password
