apiVersion: v1
kind: ConfigMap
metadata:
  name: q5
data:
  MONGO_INITDB_ROOT_USERNAME: "admin"
  MONGO_INITDB_DATABASE: "admin"
  ME_CONFIG_MONGODB_SERVER: "mongo"
  ME_CONFIG_MONGODB_PORT: "27017"
  ME_CONFIG_BASICAUTH_USERNAME: "admin"