apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-app01
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloud-app01
  template:
    metadata:
      labels:
        app: cloud-app01
    spec:
      containers:
      - name: nginx
        image: nginx:1.23.3-alpine
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: cloud-app-svc
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: cloud-app01