apiVersion: v1
kind: Service
metadata:
  name: cloud-app-svc
spec:
  selector:
    app: cloudapp01-deployment
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80