apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-app01
  namespace: ca2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloud-app01
  template:
    metadata:
      labels:
        app: cloud-app01
    spec:
      containers:
        - name: nginx
          image: nginx:1.23.3-alpine
          ports:
            - containerPort: 80
