apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv
  namespace: q10
  labels:
    type: local
spec:
  storageClassName: gp2
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteOncePod
  hostPath:
    path: "/mnt/data"
---
# PersistentVolumeClaim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc
  namespace: q10
spec:
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp2
  accessModes:
    - ReadWriteOncePod
