apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: limit
spec:
  serviceName: "redis"
  replicas: 3
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis
        resources:
          requests:
            cpu: "500m"   # 0.5 CPU
            memory: "500Mi"
          limits:
            cpu: "1"      # 1 CPU
            memory: "1Gi"