DEPLOYMENT->
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: ca1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: nginx
        image: nginx:latest


SERVICE->
apiVersion: v1
kind: Service
metadata:
  name: web-svc
  namespace: ca1
spec:
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
  type: NodePort  

  