apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: ca1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80  

---
apiVersion: v1
kind: Service
metadata:
  name: web-svc
  namespace: ca1
spec:
  type: NodePort 
  selector:
    app: web
  ports:
  - port: 8080       
    targetPort: 80   
    nodePort: 30080   

