apiVersion: apps/v1
kind: Deployment
metadata:
  name: app01-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: app01-svc
spec:
  type: NodePort
  selector:
    app: app01-svc
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080