apiVersion: apps/v1
kind: Deployment
metadata:
  name: app01
  labels:
    app: app01
  namespace: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app01
  template:
    metadata:
      labels:
        app: app01
    spec:
      containers:
        - name: app01
          image: nginx:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: app01-svc
  namespace: prod
  labels:
    app: app01
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: app01