apiVersion: v1
kind: ConfigMap
metadata:
  name: mysqlconfig
data:
  MYSQL_DATABASE: "data"
  MYSQL_USER: "data"
---
apiVersion: v1
kind: Secret
metadata:
  name: mysqlsecret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: YWRtaW4=
  MYSQL_PASSWORD: YWRtaW4=
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: state
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 3Gi
  storageClassName: state
  hostPath:
    path: /mnt/data/mysql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: state
  volumeName: mysql-pv
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-statefulset
spec:
  serviceName: mysql-statefulset
  replicas: 1
  selector:
    matchLabels:
      app: mysql-statefulset
  template:
    metadata:
      labels:
        app: mysql-statefulset
    spec:
      containers:
        - name: mysql-statefulset
          image: mysql:oraclelinux9
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysqlsecret
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysqlsecret
                  key: MYSQL_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: mysqlconfig
                  key: MYSQL_DATABASE
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: mysqlconfig
                  key: MYSQL_USER
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: mysql-storage
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: standard
        resources:
          requests:
            storage: 2Gi
