apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: state
provisioner: rancher.io/local-path  # Adjust if using a different provisioner
parameters:
  type: local-path

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: state
  hostPath:
    path: /path/to/mysql/data  # Adjust according to your environment

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: datastorage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: state

---

apiVersion: v1
kind: Secret
metadata:
  name: mysqlsecret
  namespace: datastorage
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: dGVzdAo=  # base64-encoded value
  MYSQL_PASSWORD: dGVzdAo=        # base64-encoded value

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: mysqlconfig
  namespace: datastorage
data:
  MYSQL_DATABASE: db
  MYSQL_USER: admin

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: datastorage
spec:
  serviceName: "mysql"
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:oraclelinux9
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysqlsecret
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysqlsecret
                  key: MYSQL_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: mysqlconfig
                  key: MYSQL_DATABASE
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: mysqlconfig
                  key: MYSQL_USER
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: mysql-data  # Ensure this matches the volumeMount name
        namespace: datastorage
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi
        storageClassName: state
