apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: state
provisioner: k8s.io/minikube-hostpath
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: datastorage
spec:
  serviceName: "mysql"
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:oraclelinux9
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysqlsecret
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysqlsecret
                  key: MYSQL_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: mysqlconfig
                  key: MYSQL_DATABASE
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: mysqlconfig
                  key: MYSQL_USER
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: state
        resources:
          requests:
            storage: 3Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: mysqlsecret
  namespace: datastorage
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: mysecretpassword
  MYSQL_PASSWORD: mysecretpassword
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysqlconfig
  namespace: datastorage
data:
  MYSQL_DATABASE: mydatabase
  MYSQL_USER: myuser
