apiVersion: v1
kind: ConfigMap
metadata:
  name: mysqlconfig
  namespace: datastorage
data:
  MYSQL_DATABASE: mysql
  MYSQL_USER: fawwaz
controlplane $ cat mysqlsecret.yaml 
apiVersion: v1
kind: Secret
metadata:
  name: mysqlsecret
  namespace: datastorage
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cGFzc3dvcmQK
  MYSQL_PASSWORD: cGFzc3dvcmQK