apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-state
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: state
  hostPath:
    path: /mnt/data
