apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-q12
spec:
  capacity:
    storage: 3Gi
  volumeMode: Filesystem
  hostPath:
    path: "/mnt/data/"
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: state