apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  labels:
    app: mysql-svc
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
controlplane $ cat ss.yaml 
apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  labels:
    app: mysql-svc
spec:
  ports:
  - port: 80
    name: mysql
  clusterIP: None
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-deploy
spec:
  selector:
    matchLabels:
      app: mysql-svc
  serviceName: "mysql"
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: mysql-svc
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mysql
        image: mysql:oraclelinux9
        ports:
        - containerPort: 8080
          name: mysql
        volumeMounts:
        - name: mysql
          mountPath: /var/lib/mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysqlsecret
              key: root-password
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysqlsecret
              key: password
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mysqlconfig
              key: database
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: mysqlconfig
              key: user
  volumeClaimTemplates:
  - metadata:
      name: mysql
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: state
      resources:
        requests:
          storage: 2Gi