apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: state
provisioner: csi-driver.example-vendor.example
reclaimPolicy: Retain 
allowVolumeExpansion: true
mountOptions:
  - discard 
volumeBindingMode: WaitForFirstConsumer
parameters:
  guaranteedReadWriteLatency: "true"