apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab-deployment
  labels:
    app: lab-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: lab-deployment
  template:
    metadata:
      labels:
        app: lab-deployment
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
